default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgre
  password: root

development:
  <<: *default
  database: development_codika_exercise
test:
  <<: *default
  database: test_codika_exercise
